#!/bin/bash

# GitHub Pages Deployment Quick Reference
# This script provides commands for deploying your Next.js portfolio

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  Next.js Portfolio - GitHub Pages Deployment Quick Reference  ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Color codes
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}📋 DEPLOYMENT QUICK COMMANDS${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo -e "${GREEN}1️⃣  LOCAL TESTING (Before Push)${NC}"
echo "   # Build locally"
echo "   npm run build"
echo ""
echo "   # Test production build"
echo "   npm run start"
echo "   # Visit http://localhost:3000"
echo ""

echo -e "${GREEN}2️⃣  GIT PUSH (Trigger Deployment)${NC}"
echo "   # Stage all changes"
echo "   git add ."
echo ""
echo "   # Commit changes"
echo "   git commit -m 'Deploy portfolio to GitHub Pages'"
echo ""
echo "   # Push to main branch (triggers workflow)"
echo "   git push origin main"
echo ""

echo -e "${GREEN}3️⃣  MONITOR DEPLOYMENT${NC}"
echo "   # Option A: Watch in terminal (requires gh CLI)"
echo "   gh run list"
echo ""
echo "   # Option B: View in GitHub"
echo "   Open repository → Actions tab → Monitor workflow"
echo ""

echo -e "${GREEN}4️⃣  VERIFY LIVE SITE${NC}"
echo "   # Default GitHub Pages URL"
echo "   https://divyanshu-portfolio.pages.github.io"
echo ""
echo "   # Custom domain (if configured)"
echo "   https://yourdomain.com"
echo ""

echo ""
echo -e "${BLUE}🔧 WORKFLOW FILE${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📁 Location: .github/workflows/deploy.yml"
echo ""
echo "✅ Already configured for:"
echo "   • Node.js 20+ (optimal for Next.js 16)"
echo "   • Static export via next build"
echo "   • Automatic deployment to /out directory"
echo "   • Dynamic domain support via NEXT_PUBLIC_DOMAIN"
echo ""

echo ""
echo -e "${BLUE}🌐 ENVIRONMENT VARIABLES${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Set in: Settings → Secrets and variables → Actions"
echo ""
echo "Required for custom domain:"
echo "  NEXT_PUBLIC_DOMAIN=https://yourdomain.com"
echo ""
echo "Default (if not set):"
echo "  NEXT_PUBLIC_DOMAIN=https://divyanshu-portfolio.pages.github.io"
echo ""

echo ""
echo -e "${BLUE}📂 PUBLIC/CNAME FILE${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "For custom domain:"
echo ""
echo "   1. Edit public/CNAME"
echo "   2. Add your domain: yourdomain.com"
echo "   3. Commit and push"
echo "   4. File will be preserved during deployment"
echo ""

echo ""
echo -e "${BLUE}🚨 COMMON ISSUES & SOLUTIONS${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "❌ Workflow not starting?"
echo "   ✓ Check if .github/workflows/deploy.yml exists"
echo "   ✓ Try pushing again: git push origin main"
echo "   ✓ Manually trigger: Actions → Deploy to GitHub Pages → Run workflow"
echo ""

echo "❌ Build failed with TypeScript error?"
echo "   ✓ Run locally: npm run build"
echo "   ✓ Fix errors and commit"
echo "   ✓ Push to trigger workflow again"
echo ""

echo "❌ Site shows 404 or old content?"
echo "   ✓ Wait 60 seconds for deployment to complete"
echo "   ✓ Hard refresh: Cmd+Shift+R (Mac) or Ctrl+Shift+R (Windows)"
echo "   ✓ Clear browser cache"
echo "   ✓ Check Settings → Pages for correct URL"
echo ""

echo "❌ Custom domain not working?"
echo "   ✓ Verify DNS records are set (5-48 hour delay)"
echo "   ✓ Check: https://dnschecker.org"
echo "   ✓ Verify CNAME in Settings → Pages"
echo "   ✓ Wait for certificate (5-30 minutes)"
echo ""

echo ""
echo -e "${BLUE}📊 GITHUB PAGES SETTINGS${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Verify these in Settings → Pages:"
echo ""
echo "  ✓ Source: GitHub Actions (NOT Branch)"
echo "  ✓ Enforce HTTPS: Enabled"
echo "  ✓ Custom domain: yourdomain.com (if applicable)"
echo ""

echo ""
echo -e "${BLUE}📱 TESTING CHECKLIST${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "After deployment, verify:"
echo ""
echo "  ☐ All pages load without 404 errors"
echo "  ☐ Profile image displays correctly"
echo "  ☐ All sections visible (header, about, projects, etc.)"
echo "  ☐ Links work (internal and external)"
echo "  ☐ Download button works"
echo "  ☐ Cat animation appears"
echo "  ☐ Audio plays when expected"
echo "  ☐ Mobile responsive design works"
echo "  ☐ No red errors in DevTools Console"
echo "  ☐ Open Graph preview works (share on Facebook)"
echo ""

echo ""
echo -e "${BLUE}🔗 USEFUL LINKS${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Documentation:"
echo "  • GitHub Pages: https://docs.github.com/en/pages"
echo "  • Next.js Static Export: https://nextjs.org/docs/app/building-your-application/deploying/static-exports"
echo "  • GitHub Actions: https://docs.github.com/en/actions"
echo ""
echo "Tools:"
echo "  • DNS Checker: https://dnschecker.org/"
echo "  • Lighthouse: https://developers.google.com/web/tools/lighthouse"
echo "  • Meta Tag Preview: https://www.opengraph.xyz/"
echo ""

echo ""
echo -e "${BLUE}📋 DEPLOYMENT STEPS SUMMARY${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Test locally:         npm run build && npm run start"
echo "2. Stage changes:        git add ."
echo "3. Commit changes:       git commit -m 'Deploy portfolio'"
echo "4. Push to GitHub:       git push origin main"
echo "5. Monitor in Actions:   GitHub → Actions tab"
echo "6. Verify live site:     Visit https://yourdomain.com"
echo ""

echo -e "${YELLOW}⚠️  IMPORTANT REMINDERS${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "• Public repository required for free GitHub Pages"
echo "• HTTPS is automatically enabled on GitHub Pages"
echo "• Custom domain requires DNS configuration (5-48 hours)"
echo "• CNAME file in public/ will be deployed automatically"
echo "• Static export: No backend needed, perfect for portfolio"
echo ""

echo -e "${GREEN}✅ You're all set for deployment!${NC}"
echo ""
echo "Next step: Review GITHUB_SETUP_CHECKLIST.md for detailed steps"
echo ""
